let cat = document.getElementById("Cat");
let nom = document.getElementById("N");
let photo = document.getElementById("Ph");
let destination = document.getElementById("D");
let prix = document.getElementById("prix");
let duree = document.getElementById("Dur");
let date = document.getElementById("date");
let BTNAjout = document.getElementById("BTNAjouter");
let BTNReset = document.getElementById("BTNReset");
let table = document.getElementsByTagName("table")[0];
BTNAjout.addEventListener("click",() => {
    let tr = table.insertRow();
    let td1 = tr.insertCell();
    td1.innerHTML = `${cat.value}`;
    let td2 = tr.insertCell();
    td2.innerHTML = `${nom.value}`;
    let td3 = tr.insertCell();
    td3.innerHTML = `${photo.value}`;
    let td4 = tr.insertCell();
    td4.innerHTML = `${destination.value}`;
    let td5 = tr.insertCell();
    td5.innerHTML = `${prix.value}`;
    let td6 = tr.insertCell();
    td6.innerHTML = `${duree.value}`;
    let td7 = tr.insertCell();
    td7.innerHTML = `${date.value}`;
    let btnModf = document.createElement("button");
    btnModf.setAttribute("id","BTNModf");
    btnModf.textContent = "Modifier";
    let td8 = tr.insertCell();
    td8.innerHTML = btnModf;
    let btnSupp = document.createElement("button");
    btnSupp.setAttribute("id","BTNSupp");
    btnSupp.textContent = "Supprimer";
    let td9 = tr.insertCell();
    td9.innerHTML = btnSupp;
    let haut = document.createElement("button");
    haut.setAttribute("id","H");
    haut.innerHTML = "Haut";
    let td10 = tr.insertCell();
    td10.innerHTML = haut;
    let bas = document.createElement("button");
    bas.setAttribute("id","B");
    bas.innerHTML = "Bas";
    let td11 = tr.insertCell();
    td11.innerHTML = bas;
    let input1 = document.createElement("input");
    input1.setAttribute("type","radio");
    input1.setAttribute("id","G");
    input1.innerHTML = "Gras";
    let input2 = document.createElement("input");
    input2.setAttribute("type","radio");
    input2.setAttribute("id","R");
    input2.innerHTML = "Rouge";
    let td12 = tr.insertCell();
    td12.innerHTML = `${input1} ${input2}`;
})